### ISSUE TITLE
Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by Oerroot** [Editi0/SYSU-HealthReport-Template#2]
### Actions运行失败……

> Run Editi0/SYSU-HealthReport@master
> Run pip install -r D:\a\_actions\Editi0\SYSU-HealthReport\master\requirements.txt
> Collecting requests
>   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
> Collecting retrying
>   Downloading retrying-1.3.3.tar.gz (10 kB)
> Collecting selenium
>   Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
> Collecting urllib3<1.27,>=1.21.1
>   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
> Collecting charset-normalizer~=2.0.0
>   Downloading charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
> Collecting idna<4,>=2.5
>   Downloading idna-3.2-py3-none-any.whl (59 kB)
> Collecting certifi>=2017.4.17
>   Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
> Collecting six>=1.7.0
>   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
> Using legacy 'setup.py install' for retrying, since package 'wheel' is not installed.
> Installing collected packages: urllib3, six, idna, charset-normalizer, certifi, selenium, retrying, requests
>     Running setup.py install for retrying: started
>     Running setup.py install for retrying: finished with status 'done'
> Successfully installed certifi-2021.10.8 charset-normalizer-2.0.6 idna-3.2 requests-2.26.0 retrying-1.3.3 selenium-3.141.0 six-1.16.0 urllib3-1.26.7
> 初始化selenium driver完成
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> 访问登录页面
> 读取用户名密码
> 输入用户名密码
> 识别验证码
> Traceback (most recent call last):
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
>     raise err
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
>     chunked=chunked,
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connection.py", line 358, in connect
>     conn = self._new_conn()
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
>     self, "Failed to establish a new connection: %s" % e
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D3BA819708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\util\retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cas.sysu.edu.cn', port=443): Max retries exceeded with url: /cas/captcha.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D3BA819708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\a\_actions\Editi0\SYSU-HealthReport\master\jksb_sysu.py", line 68, in <module>
>     login()
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\retrying.py", line 49, in wrapped_f
>     return Retrying(*dargs, **dkw).call(f, *args, **kw)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\retrying.py", line 212, in call
>     raise attempt.get()
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\retrying.py", line 247, in get
>     six.reraise(self.value[0], self.value[1], self.value[2])
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\six.py", line 719, in reraise
>     raise value
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\retrying.py", line 200, in call
>     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
>   File "D:\a\_actions\Editi0\SYSU-HealthReport\master\jksb_sysu.py", line 30, in login
>     code = get_img(driver, ocr_token)
>   File "D:\a\_actions\Editi0\SYSU-HealthReport\master\util.py", line 15, in get_img
>     res =  s.get(url)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests\sessions.py", line 555, in get
>     return self.request('GET', url, **kwargs)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests\sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests\sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests\adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cas.sysu.edu.cn', port=443): Max retries exceeded with url: /cas/captcha.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D3BA819708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> Error: Process completed with exit code 1.

**Comment by Editi0** [comment]
>注册第三方在线识别平台，每日免费额度100，获取 Token。

请确认这里正确完成了

**Comment by Oerroot** [comment]
> > 注册第三方在线识别平台，每日免费额度100，获取 Token。
> 
> 请确认这里正确完成了

登陆图片识别平台，显示我今日余额还有97次

**Comment by Oerroot** [comment]
> > 注册第三方在线识别平台，每日免费额度100，获取 Token。
> 
> 请确认这里正确完成了

啊这，才注意到我填的是用户的taken，不是识别图片的token……抱歉打扰了
